source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby ">= 3.3.0"

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rack-cors"
gem "devise"
gem "devise-jwt"
gem "pundit"
gem "pagy", "~> 9.0"

group :development, :test do
  gem "dotenv-rails"
  gem "debug", platforms: %i[mri windows]
  gem "rubocop-rails-omakase", require: false
  gem "brakeman", require: false
end

group :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers", "~> 6.0"
  gem "database_cleaner-active_record"
end
